const FA = "Albert Sans, system-ui, sans-serif"

export const clerkAppearance = {
  variables: {
    colorBackground:      "#FDFCF9",
    colorInputBackground: "#FFFFFF",
    colorInputText:       "#1a1917",
    colorText:            "#1a1917",
    colorTextSecondary:   "#6e6b66",
    colorPrimary:         "#1a1917",
    colorDanger:          "#8c2f4e",
    borderRadius:         "4px",
    fontFamily:           FA,
    fontSize:             "14px",
  },
  elements: {
    cardBox:  { backgroundColor: "transparent", boxShadow: "none", border: "none", borderRadius: "0", width: "100%" },
    card:     { backgroundColor: "transparent", border: "none", boxShadow: "none", borderRadius: "0", padding: "0", width: "100%" },
    header:         { display: "none" },
    headerTitle:    { display: "none" },
    headerSubtitle: { display: "none" },

    socialButtonsBlockButton: {
      backgroundColor: "#FFFFFF",
      border:          "1px solid rgba(26,25,23,0.14)",
      borderRadius:    "6px",
      color:           "#1a1917",
      fontFamily:      FA,
      height:          "52px",
      fontSize:        "14px",
      fontWeight:      "400",
      overflow:        "visible",
      position:        "relative",
    },
    socialButtonsBlockButtonText: { color: "#1a1917", fontFamily: FA, fontSize: "14px" },
    socialButtonsProviderIcon:    { width: "16px", height: "16px" },
    badge: {
      backgroundColor: "#1a1917",
      color:           "#FDFCF9",
      fontSize:        "10px",
      borderRadius:    "100px",
      padding:         "2px 8px",
    },

    dividerRow:  { margin: "20px 0" },
    dividerLine: { backgroundColor: "rgba(26,25,23,0.1)" },
    dividerText: { color: "#a09890", fontFamily: FA, fontSize: "11px", letterSpacing: "0.06em", textTransform: "uppercase" as const },

    formFields:   { gap: "4px" },
    formFieldRow: { gap: "12px" },
    formFieldLabel: {
      fontFamily: FA, color: "#6e6b66", fontSize: "11px", fontWeight: "600",
      textTransform: "uppercase" as const, letterSpacing: "0.1em", marginBottom: "5px",
    },
    formFieldInput: {
      backgroundColor: "#FFFFFF",
      border:          "1px solid rgba(26,25,23,0.14)",
      borderRadius:    "4px",
      color:           "#1a1917",
      fontFamily:      FA,
      fontSize:        "14px",
      height:          "46px",
      padding:         "0 14px",
    },
    formFieldInputShowPasswordButton: { color: "#a09890" },

    formButtonPrimary: {
      backgroundColor: "#1a1917",
      color:           "#FDFCF9",
      fontFamily:      FA,
      fontWeight:      "500",
      fontSize:        "13px",
      borderRadius:    "6px",
      height:          "52px",
      letterSpacing:   "0.06em",
      textTransform:   "uppercase" as const,
      border:          "none",
      marginTop:       "8px",
    },

    footerAction:     { marginTop: "24px", textAlign: "center" as const },
    footerActionText: { color: "#a09890", fontFamily: FA, fontSize: "13px" },
    footerActionLink: { color: "#1a1917", fontWeight: "600", fontFamily: FA, textDecoration: "underline" },

    rootBox:                   { width: "100%", maxWidth: "420px" },
    identityPreviewText:       { fontFamily: FA, color: "#1a1917", fontSize: "14px" },
    identityPreviewEditButton: { fontFamily: FA, color: "#6e6b66" },
    alertText:                 { fontFamily: FA, fontSize: "13px" },
  },
}
