/**
 * Sample scan result shown as placeholder data before the user runs a real scan.
 * Demonstrates what the workspace output looks like — useful for UI dev without a backend.
 * Edit the values here to update the demo content visible on first load.
 */

import type { ScanResult, ProfileSimulation } from "@/types/workspace"

const MOCK_SIMULATION: ProfileSimulation = {
  profiles: [
    {
      id: "exact_match",
      label: "Exact Match",
      description: "Rewards exact keyword overlap; heavily penalises missing must-have terms.",
      score: 52,
      parse_quality: 85,
      keyword_match: 38,
      adjacent_skills: 42,
      structure_confidence: 75,
      risk_level: "MEDIUM",
      top_strengths: [
        "Clean parse: résumé structure extracted with high confidence",
        "3 of 8 required terms present",
      ],
      top_failures: [
        "Missing must-have term(s): kubernetes, aws, terraform",
        "Keyword gap: 62% of required terms absent",
      ],
      lost_signals: ["'python' detected in experience body only — may be skipped without a skills block"],
      recommended_fixes: ["Add must-have keywords to résumé: kubernetes, aws, terraform", "Add a dedicated skills section"],
    },
    {
      id: "structure_sensitive",
      label: "Structure Sensitive",
      description: "Penalises ambiguous or fragmented formatting; rewards clearly parsed sections.",
      score: 61,
      parse_quality: 85,
      keyword_match: 38,
      adjacent_skills: 42,
      structure_confidence: 75,
      risk_level: "MEDIUM",
      top_strengths: [
        "All expected sections found: education, experience, skills, summary",
        "High parse confidence",
      ],
      top_failures: [
        "Missing must-have term(s): kubernetes, aws, terraform",
        "2 skills only found in prose",
      ],
      lost_signals: ["'python' detected in experience body only", "'docker' detected in experience body only"],
      recommended_fixes: ["Move 'python', 'docker' into a dedicated skills block", "Add must-have keywords"],
    },
    {
      id: "adjacent_coverage",
      label: "Transferable Skills",
      description: "Broader matching using adjacent skill inference (heuristic). Rewards transferable experience.",
      score: 67,
      parse_quality: 85,
      keyword_match: 38,
      adjacent_skills: 65,
      structure_confidence: 75,
      risk_level: "LOW",
      top_strengths: [
        "Adjacent skill signals cover most missing required terms",
        "Strong evidence density",
      ],
      top_failures: ["Partial keyword coverage: 38%"],
      lost_signals: [],
      recommended_fixes: [
        "Add explicit kubernetes and aws to skills section",
        "Add 2–3 bullets with quantified impact",
      ],
    },
  ],
  universal_fixes: [
    "Add must-have keywords to résumé: kubernetes, aws, terraform",
    "Move 'python', 'docker' from prose into a dedicated skills section",
    "Add quantified impact to 2–3 bullets (%, $, scale, or time saved)",
    "Add missing sections: summary",
  ],
  score_spread: { min: 52, max: 67, delta: 15, volatility: "MEDIUM" },
  cross_profile_summary:
    "Best in Transferable Skills (67), weakest in Exact Match (52). 15-pt spread. Exact-Match score lower due to keyword gap.",
}

const MOCK_ATS_TEXT = [
  "Jane Smith",
  "jane@email.com | linkedin.com/in/janesmith",
  "",
  "Software Engineer with 5 years of experience building distributed systems.",
  "",
  "EXPERIENCE",
  "Senior Software Engineer - Acme Corp (2021-2024)",
  "- Responsible for migration of monolith to microservices",
  "- Helped reduce infrastructure costs",
  "- Worked on CI/CD improvements",
  "",
  "SKILLS",
  "Python, JavaScript, Docker, PostgreSQL",
  "",
  "EDUCATION",
  "B.S. Computer Science - State University, 2019",
].join("\n")

export const MOCK_SCAN: ScanResult = {
  scan_id:          "mock-001",
  source_id:        "sample_resume.pdf",
  ats_text_preview: MOCK_ATS_TEXT,
  scores: {
    overall:              0.52,
    keyword_match:        0.38,
    experience_alignment: 0.70,
    parse_integrity:      0.85,
    structure:            0.75,
    quantified_impact:    0.15,
  },
  issues: [
    {
      issue_type:    "keyword_gap",
      severity:      "high",
      title:         "Missing keyword: kubernetes",
      description:   "The JD requires kubernetes but your resume does not mention it.",
      evidence:      '"kubernetes" does not appear anywhere in your résumé text.',
      fix_pattern:   'Add "kubernetes" in your Skills section or work it into a relevant experience bullet.',
      rewrite_starter: "",
      source_excerpt:  "",
      suggested_fix:   "Add kubernetes in your Skills section.",
      impact_score:    3.2,
    },
    {
      issue_type:    "low_quantification",
      severity:      "high",
      title:         "Most bullets lack measurable impact",
      description:   "4 of 4 experience bullets have no numbers or percentages.",
      evidence:      "4 of 4 experience bullets contain no numbers, percentages, currency, or scale indicators.",
      fix_pattern:   "Rewrite 2–3 bullets: add %, $, users, team size, latency ms, requests/s, cost saved, or delivery time.",
      rewrite_starter: "Migrated monolith to [N] microservices, cutting deployment time by [X%] and rollback time to [Y min].",
      source_excerpt:  "- Responsible for migration of monolith to microservices",
      suggested_fix:   "Add metrics: e.g. Migrated monolith to 12 microservices, reducing p99 latency by 35%",
      impact_score:    3.2,
    },
    {
      issue_type:    "weak_phrasing",
      severity:      "medium",
      title:         'Weak verb: "responsible for"',
      description:   "Passive phrasing reduces impact score in LLM screeners.",
      evidence:      'Phrase "responsible for" signals passive ownership. Screeners weight active verbs more heavily.',
      fix_pattern:   "Start the bullet with: Built / Led / Reduced / Delivered / Scaled + [what] + [measurable result].",
      rewrite_starter: "Migrated monolith to [N] microservices, cutting deployment time by [X%] and rollback time to [Y min].",
      source_excerpt:  "...Responsible for migration of monolith...",
      suggested_fix:   "Replace with: Led migration of monolith to 12 microservices",
      impact_score:    1.6,
    },
    {
      issue_type:    "keyword_gap",
      severity:      "high",
      title:         "Missing keyword: aws",
      description:   "The JD requires aws but your resume does not mention it.",
      evidence:      '"aws" does not appear anywhere in your résumé text.',
      fix_pattern:   'Add "aws" in your Skills section or work it into a relevant experience bullet.',
      rewrite_starter: "",
      source_excerpt:  "",
      suggested_fix:   "Add aws to your Skills section if applicable.",
      impact_score:    3.2,
    },
  ],
  missing_keywords: ["kubernetes", "aws", "terraform", "go"],
  matched_keywords: ["python", "docker", "postgresql"],
  top_fixes: [
    {
      issue_index:   0,
      issue_type:    "keyword_gap",
      title:         "Missing keyword: kubernetes",
      suggested_fix: "Add kubernetes in your Skills section.",
      fix_pattern:   'Add "kubernetes" in your Skills section.',
      labels:        ["Must-have gap", "Broad impact"],
      affects_profiles: ["exact_match", "structure_sensitive", "adjacent_coverage"],
      rank_score:    8.7,
    },
    {
      issue_index:   1,
      issue_type:    "low_quantification",
      title:         "Most bullets lack measurable impact",
      suggested_fix: "Add metrics: e.g. Migrated monolith to 12 microservices, reducing p99 latency by 35%",
      fix_pattern:   "Rewrite 2–3 bullets: add %, $, users, team size, latency ms, requests/s.",
      labels:        ["Fast win", "Quantify"],
      affects_profiles: ["exact_match", "adjacent_coverage"],
      rank_score:    6.2,
    },
    {
      issue_index:   3,
      issue_type:    "keyword_gap",
      title:         "Missing keyword: aws",
      suggested_fix: "Add aws to your Skills section if applicable.",
      fix_pattern:   'Add "aws" in your Skills section.',
      labels:        ["Broad impact"],
      affects_profiles: ["exact_match", "structure_sensitive", "adjacent_coverage"],
      rank_score:    6.7,
    },
    {
      issue_index:   2,
      issue_type:    "weak_phrasing",
      title:         'Weak verb: "responsible for"',
      suggested_fix: "Replace with: Led migration of monolith to 12 microservices",
      fix_pattern:   "Start the bullet with: Built / Led / Reduced.",
      labels:        ["Fast win"],
      affects_profiles: ["exact_match", "adjacent_coverage"],
      rank_score:    3.6,
    },
  ],
  simulation: MOCK_SIMULATION,
}
